apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local-data01
  namespace: monitoring
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/grafana"
