apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local-data01
  namespace: monitoring
  labels:
    app: grafana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
